# kubernetes 에서 사용할 API 버전(v1 은 Serviec에 사용)
apiVersion: v1 
kind: Service
metadata:
  name: frontend-service #service 이름
spec:
  selector:
    app: frontend # service 가 노출시킬 pod를 선택하는 라벨
  ports:
  - protocol: TCP # 사용할 프로토콜
    port: 80 # Service가 노출할 포트
    targetPort: 80 # Pod 대상 포트
  type: LoadBalancer #service유형 (외부에서 접근가능하도록 로드밸런서 생성)
