apiVersion: networking.k8s.io/v1 # Kubernetes Networking API버전
kind: Ingress # 리소스 종류
metadata:
  name: web-ingress #리소스 이름
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 #URL 재작성 규칙
    kubernetes.io/ingress.class: "nginx" # 사용할 Ingress 컨트롤러 지정
spec:
  rules: #Ingress 규칙 정의
  - host: www.test.com # 이 규칙이 적용될 호스트 이름
    http:
      paths: # 경로별 라우팅 규칙
      - pathType: Prefix # 경로매칭방식 (접두사 매칭)
        path: /()(.*) # 루트경로와 그이하 모든경로 매칭
        backend:
          service:
            name: frontend-service #연결할 서비스 이름
            port:
              number: 80 #서비스 포트
      - pathType: Prefix # 경로 매칭망식
        path: /api(/|$)(.*) # /api 로 시작하는 모든경로 매칭
        backend:
          service:
            name: backend-service # 연결할 서비스 이름
            port:
              number: 8000 # 서비스 포트
              